### ISSUE TITLE
Bug: Python bindings unable to find C binding DLL on Windows

### ISSUE THREAD

**Issue by Daniel-McCarthy** [GovanifY/pcsx2_ipc#4]
### Description: 
I'm attempting to use the python bindings for PINE and after building the `libpine_c.dll` from the C bindings as instructed, copying it into the location of the bindings python `example.py` script, and running it, it is unable to find the DLL.

### Details:
**Error:**
```
FileNotFoundError: Could not find module 'C:\Users\<user>\Documents\Git\pine\bindings\python\libpine_c.dll' (or one of its dependencies).
Try using the full path with constructor syntax.
```

![image](https://github.com/GovanifY/pine/assets/4957200/977a6a3d-d4c9-46dc-8e24-ffd78c9bed53)

While the DLL file is verifiably at the exact location the script is searching for it, it says that it's not found. It appears to be related to the "(or one of its dependencies)".  After further digging I found numerous cases of people experiencing this and people [pointing to python 3.8 and higher on windows having a change.](https://stackoverflow.com/questions/59330863/cant-import-dll-module-in-python) It appears to be Windows specific and specific to versions >= 3.8.0 of python. Although I have no solution as I am unsure of the dependencies or where they can be resolved from, I did want to bring this to attention.

This error occurs at [L#19 of `example.py`](https://github.com/GovanifY/pine/blob/master/bindings/python/example.py#L19) upon loading the valid DLL path into `ctypes.CDLL(...)`.

To work around this I have switched back to python 3.7.0 where with the exact same setup it is working as expected.

**Comment by GovanifY** [comment]
Does applying this diff on example.py solves the issue?
 
```diff
- libipc = ctypes.CDLL(os.path.join(os.path.dirname(os.path.abspath(__file__)),lib))
+ libipc = ctypes.CDLL(os.path.join(os.path.dirname(os.path.abspath(__file__)),lib), winmode=0)
```

**Comment by Daniel-McCarthy** [comment]
> Does applying this diff on example.py solves the issue?

Hey there, Yes it looks like it does, thanks!
When I run the script with that change I get (tested on python 3.10.0):
```
  File "C:\Users\<user>\Documents\Git\pine\bindings\python\example.py", line 26, in <module>
    print(libipc.pine_read(ipc, 0x00347D34, 0, False))
OSError: exception: access violation reading 0x00000000EE431900
```

Which I think is probably fair to assume is unrelated. It appears to get through the DLL issue I brought up so that's a valid resolution to this issue. Thanks!

**Comment by sstarbright** [comment]
I'm having a very similar access violation issue when trying to use libpine_c.dll. I copied over the code from example.py, but it just gives me access violations when trying to use the functions. Is there any way to fix this?

**Comment by GovanifY** [comment]
> I'm having a very similar access violation issue when trying to use libpine_c.dll. I copied over the code from example.py, but it just gives me access violations when trying to use the functions. Is there any way to fix this?

Hey,

Could you please give me some more information on the issues you're encountering? This seems, from the looks of it, to be a Windows only issue, which is not the development environment I use so any further detail would be appreciated.
Have you tried the patch I sent in my comment above? This seems to be a workaround for newer python windows versions.

In theory, the python bindings should "just work" given it's just C FFI calls, so it strikes me as odd that it would suddenly fully break for reasons unrelated to the comment above (in this case, an API breakage).

**Comment by sstarbright** [comment]
> Hey,
> 
> Could you please give me some more information on the issues you're encountering? This seems, from the looks of it, to be a Windows only issue, which is not the development environment I use so any further detail would be appreciated. Have you tried the patch I sent in my comment above? This seems to be a workaround for newer python windows versions.
> 
> In theory, the python bindings should "just work" given it's just C FFI calls, so it strikes me as odd that it would suddenly fully break for reasons unrelated to the comment above (in this case, an API breakage).

Sure, when I try to run the code in the example.py script, like this:

![image](https://github.com/GovanifY/pine/assets/17025229/7d05d6c6-81b8-4ecf-8fd3-dc823bbf3ad1)

I just get this access violation:
```
Traceback (most recent call last):
  File "d:\Projects\Tools\pythonpcsx2test\main.py", line 162, in StartProgram
    memory.PineMemoryHandler()
  File "d:\Projects\Tools\pythonpcsx2test\memory.py", line 15, in __init__
    print(libipc.pine_read(ipc, 0x0027DBF8, 0, False))
OSError: exception: access violation reading 0x00000000431C2A28  
```
 It doesn't happen with pine_pcsx2_new() though, just when I try to get any data from it. Like reading data from an address, or getting game information.

The version of python I'm using is 3.8.8, if that might help.

**Comment by ArsonAssassin** [comment]
Having the same issue trying to use the c bindings in a c# project

**Comment by paulo101977** [comment]
@GovanifY same error here with libipc.pine_read(ipc, 0x01FABF74, 0, False) set to 0. When I set it to 4, the error doesn't occur. Is there an offset for the memory value? I'm using the value I got from the PCSX2 debug. Is this value correct?

```
print(libipc.pine_read(ipc, 0x01FABF74, 0, False))

Cell In[1], line 335
    328 set_input_state(teclas_deste_frame)
    329 # send_keypress(win32con.VK_LEFT)
    330 # send_keypress("k")
    331 
    332 # print("before load")
    333 # vel = read_ps2_memory(0x01FABF74, 1)
    334 # print("Velocidade:", vel[0])
--> 335 print(libipc.pine_read(ipc, 0x01FABF74, 0, False))
    337 print("Error (if any): " + str(libipc.pine_get_error(ipc)))
    339 send_keypress(win32con.VK_SPACE)

OSError: exception: access violation reading 0x00000000F2E5EBF0
```

**Comment by paulo101977** [comment]
@Daniel-McCarthy @GovanifY @ArsonAssassin @sstarbright For the memory problem, I found the solution in another issue: [https://github.com/GovanifY/pine/issues/6#issuecomment-3007178325](url)
